### ISSUE TITLE
Add Bootstrap 5 tests/examples/docs

### ISSUE THREAD

**Issue by coliff** [coliff/bootstrap-show-password-toggle#3]

**Comment by FaresAhmedb** [comment]
I tried changing the Example's Bootstrap from 4.6 -> 5.0 but Unfortunately <a href="https://jsfiddle.net/mnsg2o6v/">there's an issue with with the password input field</a>

That appears to be an issue on bootstrap's side https://github.com/twbs/bootstrap/issues/25110 however the issue was for inputs with right handed add-ons. it was fixed by adding `has-validation` however that seems not to be the case here.

**Comment by coliff** [comment]
heya - I think you just need to add `rounded-end` (you can remove `rounded-right`) to the button and form input:

```html
  <div class="input-group">
      <input type="password" id="password" name="current-password" autocomplete="current-password" class="form-control rounded-end" spellcheck="false" autocorrect="off" autocapitalize="off" required>
      <button id="toggle-password" type="button" class="d-none rounded-end"
        aria-label="Show password as plain text. Warning: this will display your password on the screen.">
      </button>
    </div>
```

**Comment by FaresAhmedb** [comment]
@coliff Wow! Thank you so much. I has been trying find what is wrong for like half an hour before I wrote the reply but looks like I came to a wrong conclusion :sweat_smile:

**Comment by coliff** [comment]
:-) Happy to help. I added a Bootstrap 5 example to the project now too.

https://coliff.github.io/bootstrap-show-password-toggle/tests/bootstrap5-sign-in/
